### PR TITLE
Introduce unified docs structure from SciML, take two

### PR DESCRIPTION
**Pull request by sefffal**
**Continued from https://github.com/JuliaAstro/JuliaAstro.github.io/pull/26 Re-targeted from a branch instead of a fork to test CI preview build & deploy**

This draft PR introduces a unified doc structure based on the docs of SciML ecosystem: https://docs.sciml.ai/stable/
`ecosystem.md` is a great start that this PR builds off.

Screenshots:

## Rationale:
The JuliaAstro ecosystem already consists of many different packages. These packages are developed independently and contain their own documentation. Currently, there's no single place to browse or search across all of the packages that make up the JuliaAstro ecosystem.

## Implementation
The docs/make.jl file is augmented to loop through a list of packages. Packages from the JuliaAstro github organization are `dev`'d and built into the main docs page.
For external ecosystem packages where we don't control the repo (e.g. `CasaCore`), we just pull in the README.md instead.

### Package requirements
Packages owned by the JuliaAstro github organization must each be modified very slightly. Instead of a single `make.jl` file, they must be split into `make.jl` and `pages.jl`. The contents of e.g. `FITSIO/pages.jl` becomes:
```julia
pages   = [
    "Introduction" => "index.md",
    "API Reference" => "api.md"
]
requiredmods = Symbol[]
```
That way, we can know the structure of the sub-docs without having to run `make.jl`.
It's a quick change that I can commit to each repo whenever/if ever we are ready. We can't do this for repos outside of JuliaAstro, hence just pulling in their READMEs.

With this implementation, each package still maintains its own documentation and docs site. We just also pull them into the juliaastro.org main page. 
It's then possible to search across all packages from a single page.

## TODO
- [x] Find hack to install package doc dependencies (e.g. from Photometry.jl/docs/Project.toml)
- [ ] Write overview pages for each category
- [x] Commit `pages.jl` to each JuliaAstro repo.

The goal of this PR is just to implement the technical side. We can adjust the structure in follow-up work.

### CODE REVIEW

**Comment by mileslucas** [comment]
In response to the discussion in #26, I'm in favor if we can set up either the timed GHA, or even better if there are ways to update this package whenever there's a patch release (perhaps CompatHelper can be modified this way). Also, I'd like to see if there's a way to containerize the individual doc builds- we would probably need external help from some of the Documenter team, but I don't think it's a stopper. Having incremental builds/caching so we don't rerun the same examples again and again would be a huge time save. I wonder if other Julia orgs have accomplished this in some way.

Also a quick entry inside the website about "how to bring your package to the JuliaAstro ecosystem" might be nice, and perhaps some community guidelines, etc. This could be a separate PR, though, with more community feedback.

Thanks for putting effort into this!

**Comment by sefffal** [comment]
The PR can be previewed at: http://juliaastro.org/previews/PR27/

Currently all JuliaAstro packages with docs are being skipped until I push `pages.jl` to each of their repos, but they are building locally.

**Comment by sefffal** [comment]
I wonder if others have any thoughts on how to proceed here?
The technical approach does make us susceptible to incompatibilities between JuliaAstro packages, so for this reason I added tests that will alert us when/if that happens.
Some kind of approach that could pull and cross link the already built docs would be ideal but I don’t yet see how we could implement this.

To me this mostly a question of should the JuliaAstro organization have a bit more central planning wrt compatibility and docs, or remain as more loosely developed independent packages.


The next step would be for me to commit `pages.jl` to the other package repos so we can test building the unified docs page with CI.

**Comment by sefffal** [comment]
We talked about this today on the JuliaAstro call. The consensus was that we do want to guarantee compatibility between packages and want the unified docs structure.
I'm going ahead and committing `pages.jl` into each JuliaAstro repo. Once the docs are building here in CI we can make the final decision.

**Comment by sefffal** [comment]
I would like to revive this PR.
I'm interested in opinions about this approach vs https://github.com/JuliaComputing/MultiDocumenter.jl 

Certainly it would be nice not to have to maintain this infrastructure, but it does IMO give some quite nice results.

**Comment by mileslucas** [comment]
@sefffal The current output is quite nice, I agree with all your points. My current take is: let's run with the current implementation, once it becomes annoying enough to warrant a change we can reevaluate using a tool like MultiDocumenter. I think this is quality enough to get it out in its current state, and new packages may lag behind a bit in their inclusion, but it's better than nothing!

**Comment by sefffal** [comment]
Thanks @mileslucas! Then unless there are any objections I will clean this up and merge.

**Comment by sefffal** [comment]
Looks like DustExtinction and CCDReduction are not install-able with the latest FITSIO 0.17.

**Comment by mileslucas** [comment]
Skip CCDReduction for now, that needs some TLC from me. I'll take a look at DustExtinction today

**Comment by mileslucas** [comment]
DustExtinction should be good

**Comment by sefffal** [comment]
The current hold up is updating all packages to support FITSIO 0.17.

Since we need the latest docs of our packages, we have to build all package docs with the latest version of every core package like FITSIO.
Unfortunately, that means all sub-dependencies and their doc dependencies have to get updated version bounds every time one of these core packages gets updated.

E.g.: https://github.com/JuliaHCI/HCIDatasets.jl/pull/9

**Comment by sefffal** [comment]
This PR is building again. Unless there are any objections, I'm going to squash and merge.
The subject overview pages can be added over time.

**Pull request merged**
