### PR TITLE
Add EarthOrientation.jl, udate doc links, mention LombScargle

### PR DESCRIPTION
**Pull request by giordano**
cc @helgee

### CODE REVIEW

**Comment by giordano** [comment]
I don't know if we also want to change the mailing list to https://discourse.julialang.org/c/domain/astro

**Comment by kbarbary** [comment]
Changes look good!

I don't have a strong opinion on the mailing list; I think discourse is quite nice. However, two small drawbacks are:

- It seems like posts in "astro" also appear on the main page under "latest" where everyone sees them. It seems like a drawback to expose everyone interested in Julia with astro-specific posts. And to force people to post to a such a wide audience if they only want to reach astro people.

- It's nice to be able to see how many subscribers the mailing list has (still not very many at the moment!) to judge usage.

Maybe we should just add a link to the Discourse site and see which one is more popular for a while, then go with that.

**Comment by giordano** [comment]
> It seems like posts in "astro" also appear on the main page under "latest" where everyone sees them. It seems like a drawback to expose everyone interested in Julia with astro-specific posts. And to force people to post to a such a wide audience if they only want to reach astro people.

That's true, however much depends on how people use Discourse.  I usually open the homepage, so I see several topics on which I'm not interested, but still I find it interesting to read their title.  People that are really interested only on a specific domain can watch only that category.  They can activate email notifications for new posts created in that domain, so that they don't even need to visit the website.

Anyway, I added a link to Discourse with a [chat icon](http://fontawesome.io/icon/comment-o/).

**Comment by helgee** [comment]
Thanks for taking care of it @giordano 👍 

I think having astro-specific posts front and center on Discourse might be beneficial for Julia as a whole from a marketing perspective. Space bonus and such 🚀 😉

**Pull request merged**
