### PR TITLE
Introduce unified docs structure from SciML

### PR DESCRIPTION
**Pull request by sefffal**
This draft PR introduces a unified doc structure based on the docs of SciML ecosystem: https://docs.sciml.ai/stable/
`ecosystem.md` is a great start that this PR builds off.

Screenshots:

## Rationale:
The JuliaAstro ecosystem already consists of many different packages. These packages are developed independently and contain their own documentation. Currently, there's no single place to browse or search across all of the packages that make up the JuliaAstro ecosystem.

## Implementation
The docs/make.jl file is augmented to loop through a list of packages. Packages from the JuliaAstro github organization are `dev`'d and built into the main docs page.
For external ecosystem packages where we don't control the repo (e.g. `CasaCore`), we just pull in the README.md instead.

### Package requirements
Packages owned by the JuliaAstro github organization must each be modified very slightly. Instead of a single `make.jl` file, they must be split into `make.jl` and `pages.jl`. The contents of e.g. `FITSIO/pages.jl` becomes:
```julia
pages   = [
    "Introduction" => "index.md",
    "API Reference" => "api.md"
]
requiredmods = Symbol[]
```
That way, we can know the structure of the sub-docs without having to run `make.jl`.
It's a quick change that I can commit to each repo whenever/if ever we are ready. We can't do this for repos outside of JuliaAstro, hence just pulling in their READMEs.

With this implementation, each package still maintains its own documentation and docs site. We just also pull them into the juliaastro.org main page. 
It's then possible to search across all packages from a single page.

## TODO
- [x] Find hack to install package doc dependencies (e.g. from Photometry.jl/docs/Project.toml)
- [ ] Write overview pages for each category
- [ ] Commit `pages.jl` to each JuliaAstro repo.

The goal of this PR is just to implement the technical side. We can adjust the structure in follow-up work.

### CODE REVIEW

**Comment by sefffal** [comment]
I've got a working hack to automatically install the docs dependencies of any JuliaAstro package.
The downside is that all JuliaAstro packages have to have compatible version bounds on external docs dependencies.
E.g. if two package give docs examples using Plots, we have to be able to find a single version of Plots that satisfies both packages. I think this is not a major limitation.

**Comment by sefffal** [comment]
Actually, this came together faster than I was expecting.
In order to test the PR with CI, I'd like to commit `pages.jl` into all the JuliaAstro repos now. It's a pretty un-intrusive change so I don't foresee any issues.
Can I get some kind of go-ahead/approval to do this? I'd like to push them directly rather than go through ~20 PRs.

@giordano  @mileslucas

**Comment by mileslucas** [comment]
How would you address the problems of

1. If I update my package docs (which includes changing any doc strings) how will this repo know to update? I don't want to have docs in multiple places out-of-sync (I've seen this with a lot of the Images.jl ecosystem docs, it's frustrating)
2. CI runtime. I've noticed you're already cutting off some packages' docs because they take too long to run. This is already a lot of manual effort, essentially requiring someone to curate all of the docs, and any new package's docs. At some point it is just not feasible to have this website building tens or hundreds of docs on top of tutorials.
3. Environment management. I think it's lucky and convenient that there are currently not any package conflicts, but it definitely could happen. Is there a solution to "containerize" the environments for each doc?

**Comment by sefffal** [comment]
Hi Miles,
Thanks for your thoughtful comments.

1. This is a great point & consistency is important. It appears that we can run the docs action on a schedule: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule, perhaps every 24hrs.

2. You're right that this does limit downstream package docs from running e.g. a large suite of benchmarks. Right now the full build takes about 12 minutes. From what I can tell, CI should be able to run for up to 6hrs so lots of headroom.

3. True, if the latest JuliaAstro packages become incompatible the docs build will get stuck on the last mutually compatible versions. Maybe it would be better if the build were to fail so we get a notification. My philosophy would be that if they're "official" packages in the JuliaAstro organization they should ideally work together and the docs build can be a test of that. I guess I am volunteering to fix incompatibilities between packages as they come up. 

The idea of containerizing the docs builds in some way would be nice.

**Comment by sefffal** [comment]
Closed in favour of: https://github.com/JuliaAstro/JuliaAstro.github.io/pull/27

**Pull request closed without merging**
